name: printikum
description: a client for printing at the ikum
publish_to: 'none' 

version: 0.2.6+4

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  elbe: ^0.1.30
  http: ^1.1.0
  dartssh2: ^2.8.2
  html: ^0.15.4
  file_picker: ^7.0.2
  url_launcher: ^6.2.4
  desktop_window: ^0.4.0
  moewe: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  #ios: true
  image_path: "icon.png"
  min_sdk_android: 21 
  
  windows:
    generate: true
    image_path: "icon.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "icon_macos.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true