name: printikum
description: a client for printing at the ikum
publish_to: "none"

version: 0.3.0+8

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  elbe: ^0.1.30
  http: ^1.1.0
  dartssh2: ^2.8.2
  html: ^0.15.4
  file_picker: ^8.1.3
  url_launcher: ^6.2.4
  desktop_window: ^0.4.0
  moewe: ^0.2.5
  change_app_package_name: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  adaptive_icon_background: "#00789E"
  adaptive_icon_foreground: "assets/icon.png"
  adaptive_icon_foreground_inset: 20
  #ios
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#00789E"

  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon_macos.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
