name: 'Build Windows&Linux'

on:
  push:
    branches:
      - main

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build windows
      - name: Archive Build
        uses: actions/upload-artifact@v4
        with:
          name: printikum-windows
          path: build\windows\x64\runner\Release\
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter build linux
      - name: Archive Build
        uses: actions/upload-artifact@v4
        with:
          name: printikum-linux
          path: build/linux/x64/release/bundle